feat: add RulesTable component
POSTPUNK-TELETUBIES/new-rules-admin pull request #71
Opened 2023-10-27 00:27 UTC by jaenfigueroa

2023-10-30 07:11 UTC, Shadowrunner11 requested changes
Falta los tests unitarios

2023-10-30 07:11 UTC, Shadowrunner11 commented on src/components/RulesTable/index.tsx
> +      }}
Se esta creando esta funcion en pleno renderizado, pasarla a un componente separado

2023-10-30 07:11 UTC, Shadowrunner11 commented on src/components/RulesTable/index.tsx
> +    fetchData,
Dejar sin memo el componente y exportar por defacto con el memo y tambien el componente sin memo.
Vite impide el HRM cuando hay dos exports, considerar colcoar en archivos separados

2023-10-30 07:11 UTC, Shadowrunner11 commented on src/components/RulesTable/index.tsx
> +
Usar una abstraccion y separar responsabildiades, considerar usar servicios y en lugar de fetch una abstraccion q funcione tantno para fetch como XHR. Algo como esto
https://www.npmjs.com/package/redaxios
(Ojo, similar pero no usar el mismo primero verificar como esta la API de axios actualmente o si se peude usar un punto intermedio)

2023-10-30 07:11 UTC, Shadowrunner11 commented on src/components/RulesTable/index.tsx
> +    fetchData,
Parasar a la version 5 de reeact query, en esta la firma de useQuery es con un objeto y el key un array, para mas consistencia

2023-10-30 07:11 UTC, Shadowrunner11 commented on src/components/RulesTable/index.tsx
> +        },
pasar a sx, no usar pixeles sino usar las medidas relativas al tema (no es rem, solo son numeros)

2023-10-30 07:11 UTC, Shadowrunner11 commented on src/components/RulesTable/index.tsx
> +        placeholder: `Buscar`,
Back tildes no necesarias, pasar a comillas simples

2023-10-30 07:11 UTC, Shadowrunner11 commented on src/components/RulesTable/index.tsx
> +      muiTableContainerProps={{ sx: { minHeight: 'calc(100vh - 200px)' } }}
Usar rem

2023-10-30 07:11 UTC, Shadowrunner11 commented on src/components/RulesTable/index.tsx
> +          muiTableBodyCellProps: { sx: { padding: 0, paddingLeft: '5px' } },
Usar rem

2023-10-30 07:11 UTC, Shadowrunner11 commented on src/components/RulesTable/index.tsx
> +        showAlertBanner: Boolean(error),
Doble negacion es mas rapido q el object warpper de Boolean

2023-10-30 07:11 UTC, Shadowrunner11 commented on src/components/RulesTable/index.tsx
> +        isLoading: isLoading,
Borrrar el valor ya que tiene el mismo nombre q la llave. Tener cuidado q isLoading y isFetching no son lo mismo aproposito

2023-10-30 07:12 UTC, Shadowrunner11 commented on src/pages/Admin.tsx
> +const RulesTable = lazy(() => import('../components/RulesTable'))
Usar el router provider y una funcion generadora de rutas  para pasar directametne el lazy al atributo Component

2023-10-30 07:14 UTC, lgcarlinf commented on mocks/handlers/index.ts
eliminar ejm porfa y separar responsabilidades para eso crear factory

2023-11-03 15:09 UTC, Shadowrunner11 requested changes

2023-11-06 18:42 UTC, merged