feat: add historyLine in Drawer
POSTPUNK-TELETUBIES/new-rules-admin pull request #80
Opened 2023-11-06 15:21 UTC by ChumanY

2023-11-06 15:58 UTC, Shadowrunner11 requested changes

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/components/Drawer/CardHistory.tsx
> +interface Props {
Nombre muy generico

```suggestion
interface CardHisotryProps {
```

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/components/Drawer/CardHistory.tsx
> +  sustento: string
Pasar a ingles

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/components/Drawer/CardHistory.tsx
> +      </Typography>
Componentes repetidos, se puede abstraera un componente que s epeude llamar Subtitle por ejemplo

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/components/Drawer/CardHistory.tsx
> +        style={{ margin: '10px 0' }}
No usar style ni pixeles

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/components/Drawer/CardHistory.tsx
> +const CardHistory = (props: Props) => {
Preferir destructuracion

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/components/Drawer/CardHistory.tsx
> +const CardHistory = (props: Props) => {
Es una lambda, se peude usar el return implicito

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/components/Drawer/CardHistory.tsx
> +        color={props.action === 'Activar regla' ? 'success' : 'error'}
Las acciones no deberia estar en español y de preferencia que sea un enum en lugar de string

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/components/Drawer/SectionHistory.tsx
> +const CardHistory = lazy(() => import('./CardHistory'))
Optimizacion prematura con Lazy loading, seria mejor quitarla

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/components/Drawer/SectionHistory.tsx
> +      {/* LISTA DE USUARIOS */}
Borrar comentario

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/components/Drawer/SectionHistory.tsx
> +      {/* LINEA DE TIEMPO */}
Borrar comentario

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/components/data/history.tsx
> +  ]
Usar msw no harcodear la data mockeada

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/components/Drawer/SectionHistory.tsx
> +        <button onClick={toggleOrder}>{sortOrderText}</button>
Usar Button de material ui

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/components/Drawer/SectionHistory.tsx
> +          <Avatar />
No harcodear los avatar, que consuma tal vez de un prop un array con la data necesaria y con un map renderizar

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/stories/layouts/drawer/CardHistory.stories.tsx
> +  />
Cambiar el nombre de la variable por una q exprese la intencion

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/stories/layouts/drawer/CardHistory.stories.tsx
> +  />
Borrar este ejemplo

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/stories/layouts/drawer/CardHistory.stories.tsx
Usar el esquema de un CSF no exportar directametne

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/stories/layouts/drawer/TimelineItem.stories.tsx
> +export const Default = () => <SectionHistory />;
usar CSF y borrar este export

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/components/Drawer/SectionHistory.tsx
> +};
Remover juinto con History, usar msw. La repsonsabildiad de devolver elementos unicos es del back

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/components/Drawer/SectionHistory.tsx
> +  };
Los setters son recursos asincronos, revisar https://react.dev/reference/react/useState para actualziar correcatamente el estado para evitar problemas de desincronicacion )en este caso, usando un callback)

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/components/Drawer/SectionHistory.tsx
> +  };
Este toggler se presta mas para un useReduce

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/components/Drawer/SectionHistory.tsx
> +    if (order === 'asc') {
order deberia ser un enum y no un string

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/components/Drawer/SectionHistory.tsx
> +  const filteredHistory = HISTORY.filter((item) => selectedUsers[item.user]);
Eliminar

2023-11-06 15:58 UTC, Shadowrunner11 commented on src/components/Drawer/SectionHistory.tsx
> +    }
Usar clausula guarda

2023-11-13 02:17 UTC, Shadowrunner11 requested changes

2023-11-13 02:17 UTC, Shadowrunner11 commented on src/components/Drawer/SectionHistory.tsx
> +    const [data, setData] = useState<History[]>([]);
React query

2023-11-13 02:17 UTC, Shadowrunner11 commented on src/components/Drawer/SectionHistory.tsx
> +    const [selectedUsers, setSelectedUsers] = useState<{ [key: string]: boolean }>({});
Record<string, boolean>

2023-11-13 02:17 UTC, Shadowrunner11 commented on src/components/Drawer/SectionHistory.tsx
> +                            <Suspense fallback={<LinearProgress />}>{item.time}</Suspense>
El encargado de ordenar sera el back, o si es el fornt al final del dia esta responsabildad tendria q estar descoplada para un facil intercambio.

Por un instante pensemos que es el back xq lo q pasa es que si una regla se termina cambiado muchas veces el back no te devolvera todo el historial sino habra un limite de lo que se podra ver, por ejemplo solo los 10 ultimos movimientos o los 10 primeros, si yo orideno en el front realmente no seran ni los 10 ultimos o los 10 primeros para luego una carga perezosa, sino q estaremos ordeando la primera respuesta y dependera enteramente de lo que el back decidio traer como los 10 primeros que no necesriamente cumplen con el ordenamiento.

Por eso motivo el order es una variable q se le pasara por ejemplo al getMany como un sort, y aca hay dos formas de conseguir este comporamiento con reacQuery

La primera es que efectivamente se guarde en un estado el order para forzar un recalculod el componente al momento que cambia order y que order sea asi mismo una key de la peticion de react query. La otra forma es que esto sea controlado pero nos llevaria a algo imperativo, es decir q en lugar q se un button sea un check que visualmente se parezca a un boton y q forzemos en su onChange que dependiendo de si esta check o no se le pase imperativamente a traves de un refetch de reactQuery el order. Pero en este ultimo caso no se guardara en la cache de reactQuery la peticion haciendo que siempre este stale, es decir q siempre este vencida y nunca se usara la cache.

2023-11-13 02:17 UTC, Shadowrunner11 commented on src/components/Drawer/SectionHistory.tsx
> +                        />
Existe un compoennte Accordion en material que es una extension de Collapse que podria ocultar la logica de control

2023-11-22 21:04 UTC, Shadowrunner11 requested changes

2023-11-22 21:04 UTC, Shadowrunner11 commented on src/components/Drawer/SectionHistory.tsx
> +            return new Date(b.time).getTime() - new Date(a.time).getTime();
- En lugar de la clausula guarda se puede usar un ternario
- Preferir una funcion pura, es decir

```ts
const sortByOrder = (order)=>{
  const factor = order === Order.Ascending? -1: 1
  return ({time: prevTime}, {time: nextTime})=>factor*(new Date(prevTime) - new Date(nextTime)}
  
}
```
Ahora luego esto para q se cacule en rutime podemos inc.uso colocarlo dentro de un hook, no la logica per se, la logica para q sea reutlziable seria un utils y un hook podria ser un accesor para los componentes funcionales si se desea aprovechar q order fuerza un dispatch
```

2023-11-29 01:09 UTC, lgcarlinf requested changes

2023-11-29 01:09 UTC, lgcarlinf commented on src/components/Drawer/SectionHistory.tsx
> +            <Accordion expanded={open} onChange={handleClick}>
abstraer este componente  en un archivo a parte

2023-11-29 01:09 UTC, lgcarlinf commented on mocks/handlers/index.ts
> +    return res(ctx.status(200), ctx.json({ history }));
abstraer la siguiente logica para separar responsabilidades

2023-11-29 01:09 UTC, lgcarlinf commented on src/components/Drawer/SectionHistory.tsx
> +            <Timeline
este componente tambien

2023-11-29 01:09 UTC, lgcarlinf commented on src/components/Drawer/CardHistory.tsx
> +      {`${user}`}
aqui solamente puedes usar {user}

2023-11-29 01:09 UTC, Shadowrunner11 approved these changes

2023-11-29 05:22 UTC, lgcarlinf requested changes

2023-11-29 05:22 UTC, lgcarlinf commented on src/stories/layouts/drawer/CardHistory.stories.tsx
> +const data = createHistory(5);
no hardcodear valores

2023-11-29 05:22 UTC, lgcarlinf commented on src/stories/atoms/dataHistory.stories.tsx
> +    console.log(historyData);
eliminar console log

2023-12-01 00:21 UTC, lgcarlinf requested changes

2023-12-20 00:14 UTC, merged