feat: add rule details column
POSTPUNK-TELETUBIES/new-rules-admin pull request #82
Opened 2023-11-08 11:08 UTC by jaenfigueroa

2023-11-15 14:30 UTC, Shadowrunner11 requested changes
Los componentes deberan ser feature orientend, stroybook si los muestra como atomic desing, por lo que la estrcutra de carpetas debera cambiar.

La presentacion de las opciones de las reglas estan acopladas a un drawer, esto no deberia ser asi. El drawer es un contenedor, la presentacion del las tabs y el switch de estas debe estar separado y ser agnostico.

Para que el switcher y su body sea agnostico se puede usar un patron builder con closure, es decir una funcion que cree componentes

```tsx
interface TabSwitchOptions{
 label: RactNode;
 bodyElement: ReactNode;
}
function buildTabSwticher(tabsOptions: Record<string, TabSwitchOptions>){
   return ()=>{
       const [currentTab, setCurrentTab] = useState(()=>{
             const [ firstState ]  = Options.keys(tabsOptions)
             return first State
       ))
       
       return (
          <Box>
              <Tabs>
                 {
                    Object.keys(tabsOptions).map((key)=><Tab value={key} key={key}  label={tabsOptions[key].label}/>)
                 }
                 {
                    tabsOptions[currentTab]
                 }
               </Tabs>
            
          </Box>
       )
   }
}
```

Su uso seria 
```tsx
const TabSwitcher = buildTabSwticher({
   curation:{
    label: 'Curacion de reglas',
    bodyElement: <div>Soy el cuerpo de la curacion</div>
   },
   detail: {
     label: 'Detalle',
     bodyElement: <div> Soy el cuerpo de los detalles </div>
   }
})

<TabSwitcher  />
```

Hay una gran ventaja al usar un builder como HOF, q se podria siemplemnte pasarle un POJO de opciones y por ejemplo en el storybnook mostrar como ejemplo el caso con 3 pestanias y el caso con 2 pestanias solo haciendo plug and play en lugar de harcodear.

Sin embargo esto solo e sun ejemplo ya que por ejemplo el renderizado aca esta muyt
acoplado a una sola estraegia imperativa, es decir el cambio del cuerpo se maneja por codigo. Antes de react se manejaba con el css y el display: none. 

Entonces el builder deberia soportar ambas estrategias de renderizado, es otro trabajo de abstraccion muy necesario.

Para nuestro caso es claro q sera un csr y la verdad la estrategia de renderizado no parece importante por el momento, pero si por anticipado se coloca seria muy mantenible

2023-11-15 14:30 UTC, Shadowrunner11 commented on src/App.tsx
> +)
El header por lo general es parte del layout.
Bsaado ene l codigo del header y loq  importa su peso como codigo js tersifciado no amerita code spliting por ende tampoco lazy loading

2023-11-15 14:30 UTC, Shadowrunner11 commented on src/App.tsx
>              <Suspense fallback={<LinearProgress />}>
Los providers podrian ir en otro componente para delegar la responsabilidad solo a este

2023-11-15 14:30 UTC, Shadowrunner11 commented on src/components/atoms/Logo.tsx
> +
NOmbre generico, cambiar por LogoProps

2023-11-15 14:30 UTC, Shadowrunner11 commented on src/components/atoms/Logo.tsx
> +const Logo = ({ text = 'Pacifico' }: Props) => {
```tsx
Readonly<Props>
```

2023-11-15 14:30 UTC, Shadowrunner11 commented on src/components/atoms/Logo.tsx
> +const Logo = ({ text = 'Pacifico' }: Props) => {
La responabilidad de este componente no es la de mostrar un logo segun el contenido del codigo

2023-11-15 14:30 UTC, Shadowrunner11 commented on src/components/molecules/Header.tsx
> +const Header = ({ logo, children, ...rest }: PropsWithChildren<Props>) => {
Nombre generico, podria ser HeaderProps
```
interface HeaderProps extends BoxProps extends PropsWithChildren{
 logo: ReactNode;
}

const Header =  ({logo, children, ...props}: Readonly<JHeaderProps>)=>

2023-11-15 14:30 UTC, Shadowrunner11 commented on src/components/atoms/skeletons/SectionCuracionSkeleton.tsx
> +
Al ser un Lambda si logica, se puede usar el return implicito en lugar del explicito

2023-11-15 14:30 UTC, Shadowrunner11 commented on src/components/molecules/Header.tsx
> +      }}
el sx es themeAware, el hook se usa si no se usara sx,

```
sx={{
  background: (theme)=>....
}}
```

2023-11-15 14:30 UTC, Shadowrunner11 commented on src/components/molecules/TabSwitcher.tsx
> +}
Nombre generico

2023-11-15 14:30 UTC, Shadowrunner11 commented on src/components/molecules/TabSwitcher.tsx
> +const TabSwitcher = ({ items, ...rest }: Props) => {
Readonly

2023-11-15 14:30 UTC, Shadowrunner11 commented on src/components/molecules/TabSwitcher.tsx
> +          ))}
crypto no esta disponible ne todos los navegadores

Los keys le sirven a react para evitar re renderizados, hacerlso random hara q el 100% de veces se recree la lista.

al ser una funcion pura e peude scar del componente

2023-11-17 14:25 UTC, Shadowrunner11 requested changes
Revisar nuevamente los comentarios previos

2023-11-29 05:03 UTC, lgcarlinf requested changes

2023-11-29 05:03 UTC, lgcarlinf commented on src/components/Header/Header.tsx
> +      }}
sacar el theme de el sx en vez de usar el hook de la siguiente forma
ejm:
```
sx={(theme)=>(
  {
   background: theme.palette.primary.main
   }
)}
```

2023-12-01 00:41 UTC, lgcarlinf requested changes

2023-12-01 00:41 UTC, lgcarlinf commented on src/AppProviders.tsx
> +}
ya hay un archivo msw.ts q hace lo mismo se estaria duplicando el codigo eliminalo porfa

2023-12-11 22:31 UTC, lgcarlinf approved these changes

2023-12-11 22:38 UTC, merged